import { useState } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { useTranslation } from 'react-i18next';
import { FileDown, Loader2 } from 'lucide-react';

const langFonts = {
  en: { name: 'helvetica', url: null },
  es: { name: 'helvetica', url: null },
  fr: { name: 'helvetica', url: null },
  hi: { name: 'NotoSansDevanagari', url: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-devanagari@latest/devanagari-400-normal.ttf' },
  kn: { name: 'NotoSansKannada', url: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-kannada@latest/kannada-400-normal.ttf' },
  ta: { name: 'NotoSansTamil', url: 'https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-tamil@latest/tamil-400-normal.ttf' },
};

const localTranslations = {
  en: {
    patientInfo: "Patient Information",
    reportTitle: "CLINICAL DIAGNOSIS REPORT",
    tagline: "Predict. Explain. Trust.",
    name: "Name",
    age: "Age",
    sex: "Sex",
    reportId: "Report ID",
    male: "Male",
    female: "Female",
    aiPrediction: "AI MODEL PREDICTION",
    bloodTestValues: "Blood Test Values",
    normalRange: "Normal Range",
    normal: "Normal",
    hypothyroid: "Hypothyroid",
    hyperthyroid: "Hyperthyroid",
    explanation: "AI Explanation (SHAP Values)",
    explanationSub: "Shows which factors most influenced the prediction",
    aiNarrative: "AI Narrative",
    classProbabilities: "Class Probabilities",
    disclaimer1: "This report is generated by AI and is for informational purposes only.",
    disclaimer2: "Always consult a qualified medical professional for clinical decisions.",
    generatedBy: "Generated by XAI Thyroid Platform",
    generatingPdf: "Generating PDF...",
    downloadReport: "Download Report"
  },
  es: {
    patientInfo: "Información del Paciente",
    reportTitle: "INFORME DE DIAGNÓSTICO CLÍNICO",
    tagline: "Predecir. Explicar. Confiar.",
    name: "Nombre",
    age: "Edad",
    sex: "Sexo",
    reportId: "ID del Informe",
    male: "Masculino",
    female: "Femenino",
    aiPrediction: "PREDICCIÓN DEL MODELO DE IA",
    bloodTestValues: "Valores de Análisis de Sangre",
    normalRange: "Rango Normal",
    normal: "Normal",
    hypothyroid: "Hipotiroidismo",
    hyperthyroid: "Hipertiroidismo",
    explanation: "Explicación de IA (SHAP)",
    explanationSub: "Muestra qué factores influyeron más en la predicción",
    aiNarrative: "Narrativa de IA",
    classProbabilities: "Probabilidades de Clase",
    disclaimer1: "Este informe es generado por IA y es solo para fines informativos.",
    disclaimer2: "Consulte siempre a un profesional médico calificado para decisiones clínicas.",
    generatedBy: "Generado por la Plataforma XAI Thyroid",
    generatingPdf: "Generando PDF...",
    downloadReport: "Descargar Informe"
  },
  fr: {
    patientInfo: "Informations sur le Patient",
    reportTitle: "RAPPORT DE DIAGNOSTIC CLINIQUE",
    tagline: "Prédire. Expliquer. Confiance.",
    name: "Nom",
    age: "Âge",
    sex: "Sexe",
    reportId: "ID du Rapport",
    male: "Homme",
    female: "Femme",
    aiPrediction: "PRÉDICTION DU MODÈLE D'IA",
    bloodTestValues: "Valeurs du Bilan Sanguin",
    normalRange: "Intervalle de Référence",
    normal: "Normal",
    hypothyroid: "Hypothyroïdie",
    hyperthyroid: "Hyperthyroïdie",
    explanation: "Explication de l'IA (SHAP)",
    explanationSub: "Indique les facteurs qui ont le plus influencé la prédiction",
    aiNarrative: "Récit de l'IA",
    classProbabilities: "Probabilités de Classe",
    disclaimer1: "Ce rapport est généré par l'IA et est uniquement à titre informatif.",
    disclaimer2: "Consultez toujours un professionnel de la santé qualifié pour les décisions cliniques.",
    generatedBy: "Généré par la Plateforme XAI Thyroid",
    generatingPdf: "Génération du PDF...",
    downloadReport: "Télécharger le Rapport"
  },
  hi: {
    patientInfo: "मरीज की जानकारी",
    reportTitle: "नैदानिक ​​रिपोर्ट",
    tagline: "भविष्यवाणी। व्याख्या। विश्वास।",
    name: "नाम",
    age: "उम्र",
    sex: "लिंग",
    reportId: "रिपोर्ट आईडी",
    male: "पुरुष",
    female: "महिला",
    aiPrediction: "एआई मॉडल भविष्यवाणी",
    bloodTestValues: "रक्त परीक्षण मान",
    normalRange: "सामान्य सीमा",
    normal: "सामान्य",
    hypothyroid: "हाइपोथायरायड",
    hyperthyroid: "हाइपरथायरायड",
    explanation: "एआई स्पष्टीकरण (SHAP मान)",
    explanationSub: "यह दिखाता है कि किन कारकों ने भविष्यवाणी को सबसे अधिक प्रभावित किया",
    aiNarrative: "एआई विवरण",
    classProbabilities: "वर्ग संभावनाएँ",
    disclaimer1: "यह रिपोर्ट एआई द्वारा उत्पन्न की गई है और केवल सूचनात्मक उद्देश्यों के लिए है।",
    disclaimer2: "नैदानिक ​​निर्णयों के लिए हमेशा एक योग्य चिकित्सा पेशेवर से परामर्श करें।",
    generatedBy: "XAI थायराइड प्लेटफॉर्म द्वारा जनरेट किया गया",
    generatingPdf: "पीडीएफ जनरेट हो रहा है...",
    downloadReport: "रिपोर्ट डाउनलोड करें"
  },
  kn: {
    patientInfo: "ರೋಗಿಯ ಮಾಹಿತಿ",
    reportTitle: "ಚಿಕಿತ್ಸಕ ರೋಗನಿರ್ಣಯ ವರದಿ",
    tagline: "ಊಹಿಸಿ. ವಿವರಿಸಿ. ನಂಬಿ.",
    name: "ಹೆಸರು",
    age: "ವಯಸ್ಸು",
    sex: "ಲಿಂಗ",
    reportId: "ವರದಿ ಐಡಿ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    aiPrediction: "ಎಐ ಮಾದರಿ ಮುನ್ಸೂಚನೆ",
    bloodTestValues: "ರಕ್ತ ಪರೀಕ್ಷೆಯ ಮೌಲ್ಯಗಳು",
    normalRange: "ಸಾಮಾನ್ಯ ಶ್ರೇಣಿ",
    normal: "ಸಾಮಾನ್ಯ",
    hypothyroid: "ಹೈಪೋಥೈರಾಯ್ಡ್",
    hyperthyroid: "ಹೈಪರ್ಥೈರಾಯ್ಡ್",
    explanation: "ಎಐ ವಿವರಣೆ (SHAP ಮೌಲ್ಯಗಳು)",
    explanationSub: "ಮುನ್ಸೂಚನೆಯ ಮೇಲೆ ಯಾವ ಅಂಶಗಳು ಹೆಚ್ಚು ಪ್ರಭಾವ ಬೀರಿದವು ಎಂಬುದನ್ನು ತೋರಿಸುತ್ತದೆ",
    aiNarrative: "ಎಐ ನಿರೂಪಣೆ",
    classProbabilities: "ವರ್ಗ ಸಂಭಾವ್ಯತೆಗಳು",
    disclaimer1: "ಈ ವರದಿಯನ್ನು ಎಐ ರಚಿಸಿದೆ ಮತ್ತು ಇದು ಕೇವಲ ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ.",
    disclaimer2: "ವೈದ್ಯಕೀಯ ನಿರ್ಧಾರಗಳಿಗಾಗಿ ಯಾವಾಗಲೂ ಅರ್ಹ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    generatedBy: "XAI ಥೈರಾಯ್ಡ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಿಂದ ರಚಿಸಲಾಗಿದೆ",
    generatingPdf: "ಪಿಡಿಎಫ್ ತಯಾರಿಸಲಾಗುತ್ತಿದೆ...",
    downloadReport: "ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ"
  },
  ta: {
    patientInfo: "நோயாளி தகவல்",
    reportTitle: "மருத்துவ நோயறிதல் அறிக்கை",
    tagline: "கணிக்கவும். விளக்கவும். நம்பவும்.",
    name: "பெயர்",
    age: "வயது",
    sex: "பாலினம்",
    reportId: "அறிக்கை ஐடி",
    male: "ஆண்",
    female: "பெண்",
    aiPrediction: "AI மாதிரி கணிப்பு",
    bloodTestValues: "இரத்த பரிசோதனை மதிப்புகள்",
    normalRange: "சாதாரண வரம்பு",
    normal: "சாதாரண நிலை",
    hypothyroid: "ஹைப்போதைராய்டு",
    hyperthyroid: "ஹைப்பர்தைராய்டு",
    explanation: "AI விளக்கம் (SHAP மதிப்புகள்)",
    explanationSub: "கணிப்பை எந்த காரணிகள் அதிகம் பாதித்தன என்பதைக் காட்டுகிறது",
    aiNarrative: "AI விளக்கம்",
    classProbabilities: "வகுப்பு சாத்தியங்கள்",
    disclaimer1: "இந்த அறிக்கை AI ஆல் உருவாக்கப்பட்டது மற்றும் தகவல் நோக்கங்களுக்காக மட்டுமே.",
    disclaimer2: "மருத்துவ முடிவுகளுக்கு எப்போதும் தகுதி வாய்ந்த மருத்துவரை அணுகவும்.",
    generatedBy: "XAI தைராய்டு தளத்தால் உருவாக்கப்பட்டது",
    generatingPdf: "ಪಿடிஎಫ್ உருவாக்கப்படுகிறது...",
    downloadReport: "அறிக்கையைப் பதிவிறக்கவும்"
  }
};

const ReportDownload = ({ result, inputs, user }) => {
  const { t, i18n } = useTranslation();
  const [generating, setGenerating] = useState(false);
  const [generatingText, setGeneratingText] = useState('');

  const addGoogleFont = async (pdf, fontUrl, fontName, fontStyle = 'normal') => {
    try {
      const response = await fetch(fontUrl);
      const arrayBuffer = await response.arrayBuffer();
      
      let binary = '';
      const bytes = new Uint8Array(arrayBuffer);
      const len = bytes.byteLength;
      for (let i = 0; i < len; i++) {
        binary += String.fromCharCode(bytes[i]);
      }
      const base64 = window.btoa(binary);
      
      const fontFilename = `${fontName}-${fontStyle}.ttf`;
      pdf.addFileToVFS(fontFilename, base64);
      pdf.addFont(fontFilename, fontName, fontStyle);
      return true;
    } catch (e) {
      console.error(`Failed to load font from ${fontUrl}`, e);
      return false;
    }
  };

  const generatePDF = async () => {
    setGenerating(true);
    setGeneratingText('');

    try {
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageW = 210;
      const pageH = 297;
      const margin = 20;
      const contentW = pageW - margin * 2;
      let y = margin;

      // ── GET PREFERRED LANGUAGE & FONTS ─────────────────
      const lang = user?.preferred_lang || localStorage.getItem('lang') || i18n.language || 'en';
      const fontCfg = langFonts[lang] || langFonts.en;
      const tx = localTranslations[lang] || localTranslations.en;

      let fontName = 'helvetica';
      let isUnicodeFont = false;

      if (fontCfg.url) {
        setGeneratingText(t('result.pdf_loading_font', 'Loading font...'));
        const loaded = await addGoogleFont(pdf, fontCfg.url, fontCfg.name);
        if (loaded) {
          fontName = fontCfg.name;
          isUnicodeFont = true;
        }
      }

      const fBold = isUnicodeFont ? 'normal' : 'bold';
      const fNormal = 'normal';

      // ── HELPER FOR PAGE BREAKS ─────────────────────────
      const checkPageBreak = (neededHeight) => {
        if (y + neededHeight > pageH - margin - 15) {
          pdf.addPage();
          // Draw minimal top margin on next page
          pdf.setFillColor(255, 255, 255);
          pdf.rect(0, 0, pageW, 15, 'F');
          y = margin;
        }
      };

      // ── CAPTURE SHAP CHART IMAGE ───────────────────────
      setGeneratingText(t('result.pdf_capturing_chart', 'Capturing SHAP chart...'));
      let shapChartImg = null;
      try {
        const shapElement = document.getElementById('shap-chart-pdf-container');
        if (shapElement) {
          const canvas = await html2canvas(shapElement, {
            backgroundColor: '#0A0F1E', // Keeps premium dark dashboard styling for the chart card
            scale: 2,
            logging: false,
            useCORS: true
          });
          shapChartImg = canvas.toDataURL('image/png');
        }
      } catch (e) {
        console.error('Failed to capture SHAP chart element:', e);
      }

      setGeneratingText(t('result.pdf_building_report', 'Building report layout...'));

      // ── HEADER (CLEAN WHITE BACKGROUND) ─────────────────
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageW, 45, 'F');

      // Logo placeholder (blue circle)
      pdf.setFillColor(59, 130, 246); // #3B82F6
      pdf.circle(margin + 8, 22, 8, 'F');

      // Try to add logo image
      try {
        const img = new Image();
        img.src = '/android-chrome-512x512.png';
        await new Promise((resolve) => {
          img.onload = resolve;
          img.onerror = resolve;
          setTimeout(resolve, 800);
        });
        if (img.complete && img.naturalWidth > 0) {
          const canvas = document.createElement('canvas');
          canvas.width = img.naturalWidth;
          canvas.height = img.naturalHeight;
          canvas.getContext('2d').drawImage(img, 0, 0);
          const imgData = canvas.toDataURL('image/png');
          // Overlay logo on the placeholder circle area
          pdf.addImage(imgData, 'PNG', margin, 14, 16, 16);
        }
      } catch (e) {}

      // Brand name
      pdf.setFont(fontName, fBold);
      pdf.setFontSize(18);
      pdf.setTextColor(15, 23, 42); // Clean dark gray text
      pdf.text('XAI THYROID', margin + 20, 20);

      // Tagline
      pdf.setFont(fontName, fNormal);
      pdf.setFontSize(9);
      pdf.setTextColor(100, 116, 139); // Muted gray text
      pdf.text(tx.tagline, margin + 20, 27);

      // Report title
      pdf.setFont(fontName, fBold);
      pdf.setFontSize(10);
      pdf.setTextColor(100, 116, 139);
      pdf.text(tx.reportTitle, pageW - margin, 20, { align: 'right' });

      // Date
      pdf.setFont(fontName, fNormal);
      pdf.setFontSize(9);
      pdf.text(
        new Date().toLocaleDateString(lang === 'en' ? 'en-GB' : lang, {
          day: '2-digit', month: 'long', year: 'numeric'
        }),
        pageW - margin, 27, { align: 'right' }
      );

      y = 55;

      // ── PATIENT INFORMATION ─────────────────────────────
      pdf.setFillColor(248, 250, 252);
      pdf.roundedRect(margin, y, contentW, 40, 3, 3, 'F');
      pdf.setDrawColor(226, 232, 240);
      pdf.roundedRect(margin, y, contentW, 40, 3, 3, 'S');

      pdf.setFont(fontName, fBold);
      pdf.setFontSize(11);
      pdf.setTextColor(15, 23, 42);
      pdf.text(tx.patientInfo, margin + 5, y + 8);

      pdf.setDrawColor(59, 130, 246);
      pdf.setLineWidth(0.5);
      pdf.line(margin + 5, y + 10, margin + 55, y + 10);

      const rawSex = inputs?.sex || 'N/A';
      let displaySex = rawSex;
      if (rawSex.toLowerCase() === 'male' || rawSex.toLowerCase() === 'm') {
        displaySex = tx.male;
      } else if (rawSex.toLowerCase() === 'female' || rawSex.toLowerCase() === 'f') {
        displaySex = tx.female;
      }

      const patientData = [
        [tx.name, user?.full_name || 'Anonymous'],
        [tx.age, `${inputs?.age || 'N/A'} ${lang === 'en' ? 'years' : (lang === 'hi' ? 'वर्ष' : (lang === 'kn' ? 'ವರ್ಷಗಳು' : (lang === 'ta' ? 'ஆண்டுகள்' : (lang === 'es' ? 'años' : 'ans'))))}`],
        [tx.sex, displaySex],
        [tx.reportId, `XAI-${Date.now().toString().slice(-8)}`],
      ];

      pdf.setFont(fontName, fNormal);
      pdf.setFontSize(10);

      patientData.forEach((item, i) => {
        const col = i < 2 ? 0 : 1;
        const row = i < 2 ? i : i - 2;
        const xPos = margin + 5 + col * (contentW / 2);
        const yPos = y + 18 + row * 10;

        pdf.setTextColor(100, 116, 139);
        pdf.text(item[0] + ':', xPos, yPos);
        pdf.setTextColor(15, 23, 42);
        pdf.setFont(fontName, fBold);
        pdf.text(item[1], xPos + 25, yPos);
        pdf.setFont(fontName, fNormal);
      });

      y += 50;

      // ── DIAGNOSIS RESULT ────────────────────────────────
      const prediction = result?.prediction || 'Unknown';
      const confidence = result?.confidence || 0;

      // Color based on prediction
      let predColor = [16, 185, 129]; // green = Normal
      if (prediction === 'Hypothyroid') predColor = [239, 68, 68];
      if (prediction === 'Hyperthyroid') predColor = [245, 158, 11];

      pdf.setFillColor(...predColor);
      pdf.roundedRect(margin, y, contentW, 28, 3, 3, 'F');

      const predKey = prediction.toLowerCase();
      let displayPrediction = prediction;
      if (predKey.includes('normal')) displayPrediction = tx.normal;
      else if (predKey.includes('hypo')) displayPrediction = tx.hypothyroid;
      else if (predKey.includes('hyper')) displayPrediction = tx.hyperthyroid;

      pdf.setFont(fontName, fBold);
      pdf.setFontSize(20);
      pdf.setTextColor(255, 255, 255);
      pdf.text(displayPrediction.toUpperCase(), margin + 10, y + 13);

      pdf.setFontSize(11);
      // Backend confidence is generally 0-100 or 0-1.
      const confVal = confidence > 1 ? confidence : confidence * 100;
      pdf.text(
        `${t('result.confidence', { lng: lang })}: ${confVal.toFixed(1)}%`,
        pageW - margin - 5, y + 13, { align: 'right' }
      );

      pdf.setFont(fontName, fNormal);
      pdf.setFontSize(9);
      pdf.text(tx.aiPrediction, margin + 10, y + 22);

      y += 38;

      // ── BLOOD TEST VALUES ───────────────────────────────
      checkPageBreak(70);

      pdf.setFont(fontName, fBold);
      pdf.setFontSize(12);
      pdf.setTextColor(15, 23, 42);
      pdf.text(tx.bloodTestValues, margin, y);

      pdf.setDrawColor(59, 130, 246);
      pdf.setLineWidth(0.5);
      pdf.line(margin, y + 2, margin + 40, y + 2);

      y += 8;

      const bloodValues = [
        { label: `${t('diagnose.tsh_label', { lng: lang }) || 'TSH'}`,
          value: inputs?.tsh, unit: 'mIU/L',
          normal: '0.4 – 4.0' },
        { label: `${t('diagnose.t3_label', { lng: lang }) || 'T3'}`,
          value: inputs?.t3, unit: 'ng/dL',
          normal: '0.8 – 2.0' },
        { label: `${t('diagnose.tt4_label', { lng: lang }) || 'TT4'}`,
          value: inputs?.tt4, unit: 'μg/dL',
          normal: '60 – 140' },
        { label: `${t('diagnose.fti_label', { lng: lang }) || 'FTI'}`,
          value: inputs?.fti, unit: '',
          normal: '65 – 155' },
      ];

      bloodValues.forEach((item, i) => {
        const rowY = y + i * 14;
        const isEven = i % 2 === 0;

        if (isEven) {
          pdf.setFillColor(248, 250, 252);
          pdf.rect(margin, rowY - 4, contentW, 13, 'F');
        }

        pdf.setFont(fontName, fNormal);
        pdf.setFontSize(10);
        pdf.setTextColor(71, 85, 105);
        pdf.text(item.label, margin + 3, rowY + 4);

        pdf.setFont(fontName, fBold);
        pdf.setTextColor(15, 23, 42);
        pdf.text(
          `${item.value ?? 'N/A'} ${item.unit}`,
          margin + 110, rowY + 4
        );

        pdf.setFont(fontName, fNormal);
        pdf.setFontSize(8);
        pdf.setTextColor(100, 116, 139);
        pdf.text(
          `${tx.normalRange}: ${item.normal}`,
          pageW - margin - 3, rowY + 4, { align: 'right' }
        );
      });

      y += bloodValues.length * 14 + 8;

      // ── SHAP FEATURE IMPORTANCE ─────────────────────────
      if (shapChartImg) {
        checkPageBreak(85);

        pdf.setFont(fontName, fBold);
        pdf.setFontSize(12);
        pdf.setTextColor(15, 23, 42);
        pdf.text(tx.explanation, margin, y);

        pdf.setDrawColor(59, 130, 246);
        pdf.line(margin, y + 2, margin + 60, y + 2);

        pdf.setFont(fontName, fNormal);
        pdf.setFontSize(8);
        pdf.setTextColor(100, 116, 139);
        pdf.text(
          tx.explanationSub,
          margin, y + 8
        );

        y += 12;

        pdf.addImage(shapChartImg, 'PNG', margin, y, contentW, 65);
        y += 73;
      } else if (result?.shap_values && result.shap_values.length > 0) {
        checkPageBreak(100);

        pdf.setFont(fontName, fBold);
        pdf.setFontSize(12);
        pdf.setTextColor(15, 23, 42);
        pdf.text(tx.explanation, margin, y);

        pdf.setDrawColor(59, 130, 246);
        pdf.line(margin, y + 2, margin + 60, y + 2);

        pdf.setFont(fontName, fNormal);
        pdf.setFontSize(8);
        pdf.setTextColor(100, 116, 139);
        pdf.text(
          tx.explanationSub,
          margin, y + 8
        );

        y += 14;

        const maxShap = Math.max(
          ...result.shap_values.map(s => Math.abs(s.shap_value))
        );

        result.shap_values.slice(0, 6).forEach((shap, i) => {
          const barY = y + i * 14;
          const barMaxW = contentW * 0.5;
          const barW = Math.abs(shap.shap_value) / maxShap * barMaxW;
          const isPositive = shap.shap_value > 0;

          // Feature name
          pdf.setFont(fontName, fNormal);
          pdf.setFontSize(9);
          pdf.setTextColor(15, 23, 42);
          const shortName = shap.feature.replace(
            ' (1=Female, 0=Male)', ''
          );
          pdf.text(shortName, margin, barY + 5);

          // Bar background
          pdf.setFillColor(241, 245, 249);
          pdf.roundedRect(margin + 65, barY, barMaxW, 8, 1, 1, 'F');

          // Bar fill
          if (isPositive) {
            pdf.setFillColor(...predColor);
          } else {
            pdf.setFillColor(148, 163, 184);
          }
          if (barW > 0) {
            pdf.roundedRect(
              margin + 65, barY, barW, 8, 1, 1, 'F'
            );
          }

          // SHAP value
          pdf.setFont(fontName, fBold);
          pdf.setFontSize(8);
          pdf.setTextColor(15, 23, 42);
          pdf.text(
            shap.shap_value.toFixed(3),
            margin + 65 + barMaxW + 3, barY + 6
          );
        });

        y += result.shap_values.slice(0, 6).length * 14 + 8;
      }

      // ── AI NARRATIVE ────────────────────────────────────
      const narrativeText = result?.shap_narrative || result?.explanation;
      if (narrativeText) {
        // Estimate height
        pdf.setFont(fontName, fNormal);
        pdf.setFontSize(9);
        const testLines = pdf.splitTextToSize(narrativeText, contentW - 10);
        const narrativeH = testLines.length * 6 + 12;

        checkPageBreak(narrativeH + 12);

        pdf.setFillColor(239, 246, 255);
        pdf.setDrawColor(59, 130, 246);
        pdf.setLineWidth(0.3);

        pdf.roundedRect(margin, y, contentW, narrativeH, 3, 3, 'F');
        pdf.roundedRect(margin, y, contentW, narrativeH, 3, 3, 'S');

        pdf.setFont(fontName, fBold);
        pdf.setFontSize(10);
        pdf.setTextColor(30, 64, 175);
        pdf.text(tx.aiNarrative, margin + 5, y + 8);

        pdf.setFont(fontName, fNormal);
        pdf.setFontSize(9);
        pdf.setTextColor(30, 58, 138);
        pdf.text(testLines, margin + 5, y + 15);

        y += narrativeH + 8;
      }

      // ── PROBABILITIES ───────────────────────────────────
      if (result?.probabilities) {
        checkPageBreak(50);

        pdf.setFont(fontName, fBold);
        pdf.setFontSize(11);
        pdf.setTextColor(15, 23, 42);
        pdf.text(tx.classProbabilities, margin, y);
        y += 8;

        const classes = [
          { name: tx.normal,
            color: [16, 185, 129],
            value: result.probabilities.Normal || 0 },
          { name: tx.hypothyroid,
            color: [239, 68, 68],
            value: result.probabilities.Hypothyroid || 0 },
          { name: tx.hyperthyroid,
            color: [245, 158, 11],
            value: result.probabilities.Hyperthyroid || 0 },
        ];

        classes.forEach((cls, i) => {
          const barY = y + i * 12;
          const barW = (cls.value / 100) * (contentW * 0.6);

          pdf.setFont(fontName, fNormal);
          pdf.setFontSize(9);
          pdf.setTextColor(71, 85, 105);
          pdf.text(cls.name, margin, barY + 6);

          pdf.setFillColor(241, 245, 249);
          pdf.roundedRect(margin + 35, barY, contentW * 0.6, 8, 1, 1, 'F');

          pdf.setFillColor(...cls.color);
          if (barW > 0) {
            pdf.roundedRect(margin + 35, barY, barW, 8, 1, 1, 'F');
          }

          pdf.setFont(fontName, fBold);
          pdf.setFontSize(9);
          pdf.setTextColor(15, 23, 42);
          pdf.text(
            `${cls.value.toFixed(1)}%`,
            margin + 35 + contentW * 0.6 + 3, barY + 6
          );
        });

        y += classes.length * 12 + 8;
      }

      // ── FOOTER ──────────────────────────────────────────
      const footerY = Math.max(y + 10, pageH - 25);

      pdf.setFillColor(248, 250, 252);
      pdf.rect(0, footerY, pageW, pageH - footerY, 'F');

      pdf.setDrawColor(226, 232, 240);
      pdf.setLineWidth(0.3);
      pdf.line(margin, footerY + 3, pageW - margin, footerY + 3);

      pdf.setFont(fontName, fNormal);
      pdf.setFontSize(8);
      pdf.setTextColor(148, 163, 184);
      pdf.text(
        `\u26A0 ${tx.disclaimer1}`,
        margin, footerY + 10
      );
      pdf.text(
        tx.disclaimer2,
        margin, footerY + 15
      );
      pdf.text(
        `${tx.generatedBy} \u2014 ${new Date().toISOString().split('T')[0]}`,
        pageW - margin, footerY + 10, { align: 'right' }
      );

      // ── SAVE PDF ────────────────────────────────────────
      const namePart = user?.full_name?.replace(/\s+/g, '-') || 'Patient';
      const fileName = `XAI-Thyroid-Report-${namePart}-${new Date().toISOString().split('T')[0]}.pdf`;

      pdf.save(fileName);

    } catch (err) {
      console.error('PDF generation error:', err);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setGenerating(false);
      setGeneratingText('');
    }
  };

  const currentLang = user?.preferred_lang || localStorage.getItem('lang') || i18n.language || 'en';
  const tx = localTranslations[currentLang] || localTranslations.en;

  return (
    <button
      onClick={generatePDF}
      disabled={generating}
      className="
        flex items-center gap-2
        px-6 py-3
        rounded-xl
        border border-[rgba(255,255,255,0.08)]
        text-[#94A3B8]
        font-poppins font-medium
        text-base
        hover:border-[#3B82F6]
        hover:text-white
        hover:bg-[rgba(59,130,246,0.1)]
        transition-all duration-300
        disabled:opacity-50
        disabled:cursor-not-allowed
        w-full
        justify-center
      "
    >
      {generating ? (
        <>
          <Loader2 size={18} className="animate-spin" />
          {generatingText || tx.generatingPdf}
        </>
      ) : (
        <>
          <FileDown size={18} />
          {tx.downloadReport}
        </>
      )}
    </button>
  );
};

export default ReportDownload;
