// controllers/reportController.js — Return full record JSON for client-side PDF generation
const { DiagnosisRecord } = require('../models');
const logger = require('../utils/logger');

// ─── GET /api/v1/report/download/:record_id ─────────────────────────────────────
exports.downloadRecord = async (req, res, next) => {
  try {
    const record = await DiagnosisRecord.findOne({
      where: { id: req.params.record_id, user_id: req.user.id }, // ownership check
    });

    if (!record) {
      return res.status(404).json({ message: 'Report not found.' });
    }

    logger.info('Report downloaded', { userId: req.user.id, recordId: record.id });

    return res.status(200).json({
      report: {
        id: record.id,
        patient: {
          full_name: req.user.full_name,
          email: req.user.email,
        },
        inputs: {
          tsh: record.tsh,
          t3: record.t3,
          tt4: record.tt4,
          fti: record.fti,
          age: record.age,
          sex: record.sex,
        },
        result: {
          prediction: record.prediction,
          confidence: record.confidence,
          shap_values: record.shap_values,
          shap_narrative: record.shap_narrative,
        },
        generated_at: record.created_at,
        disclaimer:
          'This report is generated by an AI system and is NOT a substitute for clinical diagnosis. Please consult a qualified healthcare provider.',
      },
    });
  } catch (err) {
    next(err);
  }
};
